name: CI

on:
  - pull_request
  - push

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-24.04
        php-version:
          - 8.3

    name: CI

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: none, ctype, curl, dom, json, mbstring, opcache, openssl, simplexml, tokenizer, xml, xmlwriter, zip

      - name: Composer
        run: composer update --optimize-autoloader --no-interaction --no-progress --no-scripts

      - name: Reproduction
        run: ./vendor/bin/phpstan analyse --ansi -v x.php
